apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: latte-art
profiles:
- name: dev
  manifests:
    rawYaml:
    - deploy-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - deploy-prod.yaml
deploy:
  cloudrun: {}