apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: latte-art-pipeline
description: application deployment pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: [dev]
 - targetId: prod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: Cloud Run development service
run:
 location: "projects/$PROJECT_ID/locations/europe-west4"
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: Cloud Run PROD service
run:
 location: "projects/$PROJECT_ID/locations/europe-west4"